language: ruby

cache:
  bundler: true
  directories:
    - sunspot/vendor/bundle
    - sunspot_solr/vendor/bundle
    - sunspot_rails/vendor/bundle

rvm:
  - 2.1.0
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.3
  - ruby-head
  # - rbx-2.0
  # - jruby

jdk:
  - openjdk8

env:
  - GEM=sunspot UPDATE_FORMAT=xml
  - GEM=sunspot UPDATE_FORMAT=json
  - GEM=sunspot_rails UPDATE_FORMAT=xml
  - GEM=sunspot_rails UPDATE_FORMAT=json
  - GEM=sunspot_solr

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  #  https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - ci/travis.sh

